import { dateKey } from './dates';
import type { EntriesMap } from '../types';

const daysAgo = (n: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return dateKey(d);
};

export const DEMO_SEED: EntriesMap = {
  [daysAgo(0)]: {
    suicidal_behavior: false,
    self_harm_behavior: false,
    substances: false,
    suicidal_thoughts: false,
    self_harm_thoughts: false,
    guilt: 2,
    shame: 1,
    fear: 3,
    joy: 4,
    sadness: 2,
    anger: 1,
    skills: ['mindfulness', 'grounding', 'selfSoothe'],
    notes: 'Felt anxious in the morning but used grounding — it helped a lot.',
  },
  [daysAgo(1)]: {
    suicidal_behavior: false,
    self_harm_behavior: false,
    substances: false,
    suicidal_thoughts: false,
    self_harm_thoughts: false,
    guilt: 1,
    shame: 2,
    fear: 2,
    joy: 3,
    sadness: 3,
    anger: 2,
    skills: ['emotionRegulation', 'wise_mind'],
    notes: '',
  },
  [daysAgo(2)]: {
    suicidal_behavior: false,
    self_harm_behavior: false,
    substances: false,
    suicidal_thoughts: false,
    self_harm_thoughts: false,
    guilt: 3,
    shame: 3,
    fear: 1,
    joy: 2,
    sadness: 4,
    anger: 3,
    skills: ['distressTolerance', 'radicalAcceptance', 'tipp'],
    notes: 'Hard day. Used TIPP to get through a rough moment.',
  },
  [daysAgo(3)]: {
    suicidal_behavior: false,
    self_harm_behavior: false,
    substances: false,
    suicidal_thoughts: false,
    self_harm_thoughts: false,
    guilt: 1,
    shame: 1,
    fear: 1,
    joy: 5,
    sadness: 1,
    anger: 0,
    skills: ['mindfulness', 'interpersonal'],
    notes: 'Good day overall. Therapy session went well.',
  },
  [daysAgo(4)]: {
    suicidal_behavior: false,
    self_harm_behavior: false,
    substances: false,
    suicidal_thoughts: false,
    self_harm_thoughts: false,
    guilt: 2,
    shame: 2,
    fear: 3,
    joy: 2,
    sadness: 3,
    anger: 4,
    skills: ['oppositeAction', 'grounding'],
    notes: '',
  },
  [daysAgo(5)]: {
    suicidal_behavior: false,
    self_harm_behavior: false,
    substances: false,
    suicidal_thoughts: false,
    self_harm_thoughts: false,
    guilt: 1,
    shame: 1,
    fear: 2,
    joy: 4,
    sadness: 2,
    anger: 1,
    skills: ['selfSoothe', 'wise_mind', 'mindfulness'],
    notes: 'Practiced mindfulness before bed — slept better.',
  },
  [daysAgo(6)]: {
    suicidal_behavior: false,
    self_harm_behavior: false,
    substances: false,
    suicidal_thoughts: false,
    self_harm_thoughts: false,
    guilt: 0,
    shame: 0,
    fear: 1,
    joy: 5,
    sadness: 0,
    anger: 0,
    skills: ['mindfulness'],
    notes: 'Great day.',
  },
};
